name: Run Update library and Create PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: yarn install

      - name: Run Script and Commit Changes
        run: ./dev/scripts/update-library.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          add-paths: |
            package.json
            src/rpc
          commit-message: 'feat: update rpc methods with bitcoin core ${{ env.VERSION_TAG }}'
          title: 'feat: update rpc methods with bitcoin core ${{ env.VERSION_TAG }}'
          body: |
            This PR updates rpc methods in src/rpc folder and the package version to ${{ env.VERSION_TAG }}.

          labels: auto-merge
